# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 21:59
from __future__ import unicode_literals

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('code', models.CharField(default=customers.models.generate_code, editable=False, max_length=4, verbose_name='code')),
            ],
        ),
    ]
