# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 17:07
from __future__ import unicode_literals

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default=customers.models.generate_code, editable=False, max_length=4, unique=True, verbose_name='code'),
        ),
    ]
